name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust the region as needed

    - name: Sync files to S3
      run: |
        aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }}/

    - name: Set Cache-Control headers
      run: |
        aws s3api list-objects-v2 --bucket ${{ secrets.AWS_S3_BUCKET }} --query 'Contents[].{Key: Key}' --output text | while read -r key; do
          aws s3api copy-object --bucket ${{ secrets.AWS_S3_BUCKET }} --copy-source ${{ secrets.AWS_S3_BUCKET }}/$key --key $key --metadata-directive REPLACE --cache-control "max-age=0, no-cache, no-store, must-revalidate";
        done

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DIST_ID }} --paths "/*"
